<?xml version="1.0" encoding="utf-8"?>
<package format="3">
  <name>aslam_backend</name>
  <version>0.0.1</version>
  <description>aslam_backend</description>
  <maintainer email="paulfurgale@mavt.ethz.ch">Paul Furgale</maintainer>
  <author>Paul Furgale</author>
  <license>New BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>sparse_block_matrix</depend>
  <depend>sm_boost</depend>
  <depend>sm_random</depend>
  <depend>sm_timing</depend>
  <depend>sm_logging</depend>
  <depend>sm_property_tree</depend>
  <depend>tbb</depend>
</package>