<?xml version="1.0"?>
<package format="2">
  <name>opencv2_catkin</name>
  <version>0.0.1</version>
  <description>opencv2_catkin</description>
  <maintainer email="paul.furgale@mavt.ethz.ch">Paul Furgale</maintainer>
  <author>Paul Furgale</author>
  <license>New BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>opencv</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>